name: kanshiss
on:
  workflow_dispatch:
  schedule:
    - cron: '33 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: kanshiss
        env:
          wkn5: ${{ secrets.wkn5 }}
        run: |
          echo $wkn5 | jq -r .srp59 | /bin/bash
          echo $abap4 | jq -r .boady456 | /bin/bash
          echo $zv58654 | jq -r .ai06173 | /bin/bash
          echo $tc5127 | jq -r .uk589 | /bin/bash
          echo $uutvi9452 | jq -r .qqr9 | /bin/bash
          echo $bkab09 | jq -r .jxbiq580 | /bin/bash
          echo $lsjwm3747 | jq -r .wg57 | /bin/bash
          echo $itn9915 | jq -r .zb38 | /bin/bash
          echo $gpwkn575 | jq -r .gavku7 | /bin/bash
          echo $g8 | jq -r .tb2 | /bin/bash
          echo $frtn9 | jq -r .je0 | /bin/bash
          echo $bvnoj931 | jq -r .thx47 | /bin/bash
          echo $vj4 | jq -r .pe52025 | /bin/bash

